### ISSUE TITLE
一般使用者登入時，直接顯示一個更改 password 畫面

### ISSUE THREAD

**Issue by wycc** [JaeggerJose/AI_Centre_Admin#1]
一般使用者登入時，直接顯示一個更改密碼畫面。
![image](https://github.com/JaeggerJose/AI_Centre_Admin/assets/457473/04b7f6e8-1a73-4c7a-a01b-aadf43f71a34)

**Comment by JaeggerJose** [comment]
The commits a216008 and ef928c1 solved the issue and it was deployed on [this website](http://120.126.23.245:30841/)
