### ISSUE TITLE
Delete 問題

### ISSUE THREAD

**Issue by Poopogen** [JaeggerJose/AI_Centre_Admin#4]
目前delete的狀況:
Delete 單個user 會 delete 整個系統的user 。
Delete 單個 group, 如group A 內有group B 的 user, delete Group A 同時會刪掉Group B內的user。 

(未來用remove)

**Comment by wycc** [comment]
delete will remove user from the group only. If all groups are deleted, we will remove the user and its associated kubeflow profile.

**Comment by JaeggerJose** [comment]
this issue was fix by the commit 5ed0795
